name: Deploy to Heroku (Frontend)

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/frontend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add frontend remote origin
        run: git remote add heroku-frontend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_FRONTEND_APP_NAME }}.git
      - name: Deploy frontend to Heroku
        run: git push heroku-frontend `git subtree split --prefix app main`:refs/heads/main --force